// Code generated by MockGen. DO NOT EDIT.
// Source: ./network.go
//
// Generated by this command:
//
//	mockgen -typed -destination=network_mock.go -package=electrum -source=./network.go
//

// Package electrum is a generated GoMock package.
package electrum

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransport is a mock of Transport interface.
type MockTransport struct {
	ctrl     *gomock.Controller
	recorder *MockTransportMockRecorder
	isgomock struct{}
}

// MockTransportMockRecorder is the mock recorder for MockTransport.
type MockTransportMockRecorder struct {
	mock *MockTransport
}

// NewMockTransport creates a new mock instance.
func NewMockTransport(ctrl *gomock.Controller) *MockTransport {
	mock := &MockTransport{ctrl: ctrl}
	mock.recorder = &MockTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransport) EXPECT() *MockTransportMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTransport) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTransportMockRecorder) Close() *MockTransportCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTransport)(nil).Close))
	return &MockTransportCloseCall{Call: call}
}

// MockTransportCloseCall wrap *gomock.Call
type MockTransportCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTransportCloseCall) Return(arg0 error) *MockTransportCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTransportCloseCall) Do(f func() error) *MockTransportCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTransportCloseCall) DoAndReturn(f func() error) *MockTransportCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Errors mocks base method.
func (m *MockTransport) Errors() <-chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Errors")
	ret0, _ := ret[0].(<-chan error)
	return ret0
}

// Errors indicates an expected call of Errors.
func (mr *MockTransportMockRecorder) Errors() *MockTransportErrorsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errors", reflect.TypeOf((*MockTransport)(nil).Errors))
	return &MockTransportErrorsCall{Call: call}
}

// MockTransportErrorsCall wrap *gomock.Call
type MockTransportErrorsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTransportErrorsCall) Return(arg0 <-chan error) *MockTransportErrorsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTransportErrorsCall) Do(f func() <-chan error) *MockTransportErrorsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTransportErrorsCall) DoAndReturn(f func() <-chan error) *MockTransportErrorsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Responses mocks base method.
func (m *MockTransport) Responses() <-chan []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Responses")
	ret0, _ := ret[0].(<-chan []byte)
	return ret0
}

// Responses indicates an expected call of Responses.
func (mr *MockTransportMockRecorder) Responses() *MockTransportResponsesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Responses", reflect.TypeOf((*MockTransport)(nil).Responses))
	return &MockTransportResponsesCall{Call: call}
}

// MockTransportResponsesCall wrap *gomock.Call
type MockTransportResponsesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTransportResponsesCall) Return(arg0 <-chan []byte) *MockTransportResponsesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTransportResponsesCall) Do(f func() <-chan []byte) *MockTransportResponsesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTransportResponsesCall) DoAndReturn(f func() <-chan []byte) *MockTransportResponsesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendMessage mocks base method.
func (m *MockTransport) SendMessage(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockTransportMockRecorder) SendMessage(arg0 any) *MockTransportSendMessageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockTransport)(nil).SendMessage), arg0)
	return &MockTransportSendMessageCall{Call: call}
}

// MockTransportSendMessageCall wrap *gomock.Call
type MockTransportSendMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTransportSendMessageCall) Return(arg0 error) *MockTransportSendMessageCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTransportSendMessageCall) Do(f func([]byte) error) *MockTransportSendMessageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTransportSendMessageCall) DoAndReturn(f func([]byte) error) *MockTransportSendMessageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
